package com.pf.perfios.model.entity;

public enum MasReqStatus {

    TRANSACTION_INITIATED,
    FAILED_WHILE_INITIATING_TRANSACTION,
    FAILED_WHILE_UPLOADING_FILES,
    FAILED_WHILE_PROCESSING_STATEMENTS,
    FAILED_WHILE_GENERATING_REPORT,

    API_FAILURE,
    REPORT_COMPLETED,
    FAILED_SAVING_REPORT,

    ERROR_FROM_PERFIOS
}
